name: hackathon_lviv
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  freezed_annotation: ^0.15.0
  provider: ^6.0.1
  rxdart: ^0.27.2
  google_sign_in: ^5.2.1
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.0
  json_annotation: ^4.3.0
  intl: ^0.17.0
  google_maps_flutter: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.15.1+1
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true